language: node_js
node_js:
  - "7"

services:
  - docker

script: ./auto/dev-environment yarn ci

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then auto/docker-build-release; fi
