version: '2'

services:
  group-mailer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    command: npm start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
